spring:
  application:
    name: gateway-service
  cloud:
    compatibility-verifier:
      enabled: false
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/v1/user/**
        - id: wordgroup-service
          uri: lb://wordgroup-service
          predicates:
            - Path=/v1/wordgroup/**
      discovery:
        locator:
          enabled: true
server:
  port: 1500

eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true

management:
  tracing:
    sampling:
      probability: 1
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: info