version: '3.8'

services:
  db:
    image: postgres:16.2-alpine
    environment:
      POSTGRES_DB: userdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "1400:5432"

  myapp:
    build: .
    ports:
      - "1300:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://userdb:1400/userdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123

volumes:
  db-data: